#ifndef MIDI_CONSTANTS_HEADER
#define MIDI_CONSTANTS_HEADER

#define MIDI_CHUNK_TYPE_HEADER    "MThd"
#define MIDI_CHUNK_TYPE_TRACK     "MTrk"
#define MIDI_HEADER_CHUNK_LENGTH  6
#define MIDI_FORMAT_MULTI_TRACK   1
#define MIDI_TICKS_PER_QUARTER    480

#define MIDI_PERCUSSION_CHANNEL 9
#define MIDI_DEFAULT_VELOCITY   0x40

#endif
